POST http://localhost:8080/orders/enqueue
Content-Type: text/plain

MjAyMS0wMy0yNC8vbW9jayB1c2VyQG1vY2sgYnJva2VyLy8w

###
POST http://localhost:8080/orders/enqueue
Content-Type: text/plain

MjAyMS0wMy0yNC8vbW9jayB1c2VyQG1vY2sgYnJva2VyLy8x

###
POST http://localhost:8080/orders/enqueue/all
Content-Type: text/plain

mock user@mock broker