spring:
  datasource:
    url: jdbc:h2:mem:jpadb
    driverClassName: org.h2.Driver
    username: ${DB_USER:sa}
    password: ${DB_PASS:}
  jpa:
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.H2Dialect}
    open-in-view: false
    hibernate:
      ddl-auto: create
