#一个系统支持的账户
POST localhost:80/accounts/activate
Content-Type: application/json
account: mock user@mock broker

{
  "accountId" : "mock user@mock broker",
  "config": ""
}
###
#一个系统支持的账户
POST localhost:80/accounts/activate
Content-Type: application/json
account: mock user2@mock broker

{
"accountId" : "mock user2@mock broker",
"config": ""
}

###
#一个不存在的账户
POST localhost:80/accounts/activate
Content-Type: application/json
account: mock user@mock broker

{
  "accountId" : "not exist@mock broker",
  "config": ""
}

###
#一个不存在的券商
POST localhost:80/accounts/activate
Content-Type: application/json
account: mock user@mock broker

{
  "accountId" : "not exist@not exist",
  "config": ""
}

###
#一个不合法的账号
POST localhost:80/accounts/activate
Content-Type: application/json
account: mock user@mock broker

{
  "accountId" : "invalid",
  "config": ""
}