###
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "000001.SZ",
  "shares": 10,
  "price": "2.000"
}

###
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "000001.SZ",
  "shares": -10,
  "price": "2.000"
}

###
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "000001.SZ",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user2@mock broker"
}

####
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "000001.SZ",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

###
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "000002.SZ",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

#####
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "000002.SZ",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

####
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "000003.SZ",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

####
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "000003.SZ",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}
###
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "000004.SZ",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

####
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "000004.SZ",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}
###
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "000005.SZ",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

####
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "000005.SZ",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}
###
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "000006.SZ",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

####
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "000006.SZ",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}
