#xtp 测试盘
POST localhost:80/orders/
Content-Type: application/json
account: 15011348@xtp

{
  "stockCode": "000002.SZ",
  "shares": -400,
  "price": "27.68"
}

###
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "stock 1",
  "shares": -10,
  "price": "2.000"
}

###
POST localhost:80/orders/
Content-Type: application/json
account: mock user2@mock broker

{
"stockCode": "stock 1",
"shares": -10,
"price": "2.000",
"accountId": "mock user2@mock broker"
}

####
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "stock 1",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

###
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "stock 2",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

#####
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "stock 2",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

####
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "stock 3",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

####
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "stock 3",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}
###
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "stock 4",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

####
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "stock 4",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}
###
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "stock 5",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

####
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "stock 5",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}
###
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "stock 6",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

####
POST localhost:80/orders/
Content-Type: application/json
account: mock user@mock broker

{
  "stockCode": "stock 6",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}