apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade
spec:
  template:
    spec:
      containers:
        - name: trade
          image: trade-empty:1.0-SNAPSHOT
          env:
          - name: MYSQL_HOST
            value: mysql-central
      nodeSelector:
        location: central