apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: location
              operator: In
              values:
                - mock-mock-user