apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade
spec:
  template:
    spec:
      containers:
        - name: trade
          image: trade-mock:1.0-SNAPSHOT
          env:
            - name: MOCK_USERS_0_username
              value: mock user
            - name: MYSQL_HOST
              value: mysql-mock-mock-user
      nodeSelector:
        location: mock-mock-user