apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -mock-mock-user
commonLabels:
  broker: mock
  account: mock-user
bases:
  - ../../base
patchesStrategicMerge:
  - deployment.yml