#一个系统支持的账户
POST localhost:8080/accounts/activate
Content-Type: application/json

{
  "accountId" : "mock user@mock broker",
  "config": ""
}

###
#一个不存在的账户
POST localhost:8080/accounts/activate
Content-Type: application/json

{
  "accountId" : "not exist@mock broker",
  "config": ""
}

###
#一个不存在的券商
POST localhost:8080/accounts/activate
Content-Type: application/json

{
  "accountId" : "not exist@not exist",
  "config": ""
}

###
#一个不合法的账号
POST localhost:8080/accounts/activate
Content-Type: application/json

{
  "accountId" : "invalid",
  "config": ""
}