POST localhost:8080/orders/
Content-Type: application/json

{
  "stockCode": "stock 1",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

####
POST localhost:8080/orders/
Content-Type: application/json

{
  "stockCode": "stock 1",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

###
POST localhost:8080/orders/
Content-Type: application/json

{
  "stockCode": "stock 2",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

#####
POST localhost:8080/orders/
Content-Type: application/json

{
  "stockCode": "stock 2",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

####
POST localhost:8080/orders/
Content-Type: application/json

{
  "stockCode": "stock 3",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

####
POST localhost:8080/orders/
Content-Type: application/json

{
  "stockCode": "stock 3",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}
###
POST localhost:8080/orders/
Content-Type: application/json

{
  "stockCode": "stock 4",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

####
POST localhost:8080/orders/
Content-Type: application/json

{
  "stockCode": "stock 4",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}
###
POST localhost:8080/orders/
Content-Type: application/json

{
  "stockCode": "stock 5",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

####
POST localhost:8080/orders/
Content-Type: application/json

{
  "stockCode": "stock 5",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}
###
POST localhost:8080/orders/
Content-Type: application/json

{
  "stockCode": "stock 6",
  "shares": -10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}

####
POST localhost:8080/orders/
Content-Type: application/json

{
  "stockCode": "stock 6",
  "shares": 10,
  "price": "2.000",
  "accountId": "mock user@mock broker"
}